environment:
  distributed: True
  backend: 'nccl'

checkpoint:
  monitor: 'loss'
  save_every: 1
  max_to_keep: 10
  initial_value_threshold: 0.2
  verbose: True

model:
  name: 'LSTM'
  input_size: 2
  hidden_size: 128
  num_layers: 2
  batch_first: True
  dropout: 0.0
  bidirectional: False

optimizer:
  type: 'Adam'
  params:
    lr: 0.0003

dataset:
  input_folder: "../dataset/test/04"
  output_folder: "../output/chirikov02_loss_2048/lstm/SmoothL1Loss"
  sequence_length: 2048
  num_trajectories:
  trajectories: 'all'

dataloader:
  batch_size: 32
  num_workers: 1
  persistent_workers: True

trainer:
  loss: 'SmoothL1Loss'
  metrics: 'SmoothL1'
  epochs: 100
  save_img_every: 10
  gpu_id:
  verbose: True
